services:
  - type: web
    name: engagevault
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0