services:
  - type: web
    name: engagevault
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_server:app
    envVars:
      - key: BOT_TOKEN
        value: 7929001260:AAG_EZTbt3C11GCZauaLqkuP99YKkxB1NJg